### ISSUE TITLE
Problem after latest update 0.0.64

### ISSUE THREAD

**Issue by rhoddan** [10der/node-red-contrib-fibaro-hc2#2]
Just updated to latest. Needed to enter configuration again. Get rooms data error 401 and nothing is working...

**Comment by rhoddan** [comment]
It seems to work now - hc2 had locked the account but I have now problem with the device node.
In old version I just configure it as deviceid/value but now I got a message that the node is configured incorrectly...

**Comment by 10der** [comment]
I am very sorry if I've caused you any inconvenience. but I had to do it (decomposition).
but now you can simple once configure HC2 access and use it in any modules.
Again, I'm sorry.

**Comment by 10der** [comment]
but strange.

now I have upgraded my test node-red env. and no HC2 locked the account.
all nodes stopped and waiting for configure

![wzo3igtb9p 1](https://user-images.githubusercontent.com/7056498/45924902-b19de900-bf13-11e8-9c4c-0a495c12ee4c.png)

**Comment by 10der** [comment]
but yes! 
Issue in HC-DEVICE!
on it!

**Comment by rhoddan** [comment]
Thanks! No problem with new configuration (I didn’t know if you knew it)
However - When all configured and I press the poll (or reset) nothing happened in debug

**Comment by 10der** [comment]
for some reasons I am trying to prevent poll HC2 with bad creds (I think you understand me why :))))) 
so after node recvd error node locked this state.
so, please drag node left - right :))) and press -publish again.

**Comment by 10der** [comment]
when all OK node should have a green dot and label init: your HC2 name

**Comment by rhoddan** [comment]
> for some reasons I am trying to prevent poll HC2 with bad creds (I think you understand me why :)))))
> so after node recvd error, node lock this state.
> so, please drag node left - right :))) and press -publish again.

Working 🕺

**Comment by 10der** [comment]
I hope Fibaro will fix a stupid issue with bad creds HC2 API.

**Comment by 10der** [comment]
build .66 - fixed all known issue! :)

**Comment by rhoddan** [comment]
> build .66 - fixed all known issues! :)

Thanks a lot - works perfectly!

**Comment by rhoddan** [comment]
just a small note - It's some info missing in the info tab for device
![capture](https://user-images.githubusercontent.com/33499995/45929486-c64da180-bf52-11e8-8080-97bc9d5130cc.JPG)

**Comment by 10der** [comment]
this node is //TODO.
sorry, I'm working on it.


![brhgdm35rs 1](https://user-images.githubusercontent.com/7056498/45929520-ba1a1200-bf5b-11e8-85df-5b1df5d6d9e0.png)
